name: Build and Deploy to Test-PyPI
on: [workflow_dispatch]

jobs:
  build_and_deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: make setup

      - name: Build the Package
        run: make build

      - name: Verify the distribution
        run: make verify

      - name: Upload to PyPI
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.BOOTSTRAP_TEST_PYPI }}
          poetry publish -r test-pypi --skip-existing -vv --no-interaction
